apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-kiro-demo
  region: us-west-1
  version: "1.33"

managedNodeGroups:
  - name: managed-nodes
    instanceType: m5.large
    desiredCapacity: 3
    minSize: 1
    maxSize: 4
    volumeSize: 20
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        certManager: true
        efs: true
        ebs: true
        fsx: true
        cloudWatch: true

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]